services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    command: ["--replSet", "myReplicaSet"] # Optional: Add additional options if needed
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
